### ISSUE TITLE
这是怎么回事

### ISSUE THREAD

**Issue by wushal-117** [zzyser/bilibiliPyCrawler#1]
Traceback (most recent call last):
  File "E:/Microsoft edge 下载/bilibiliPyCrawler-main/MainFunction.py", line 16, in <module>
    BFS_sampling(sampling_node_number, start_id)
  File "E:\Microsoft edge 下载\bilibiliPyCrawler-main\GraphSamplingAlgorithms.py", line 26, in BFS_sampling
    print(node_list[pointer])
IndexError: list index out of range

**Comment by zzyser** [comment]
IndexError: list index out of range

**Comment by zzyser** [comment]
数组越界了，找找print(node_list[pointer])中的pointer哪里出问题了
